In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [18]:
df = pd.read_csv('iqa-csv/ioa_annotations_20260324_221133.csv')
df.head()

,Operator,Audio File,Start,Stop,Label,Timestamp,Comments
0,Simon,call_20240919_023.wav,71.0,73.0,LOCATION,2026-03-24 21:10:34,NaN
1,Simon,call_20240919_023.wav,67.0,69.0,LOCATION,2026-03-24 21:10:34,NaN
2,Simon,call_20240919_023.wav,55.0,60.0,LOCATION,2026-03-24 21:10:34,NaN
3,Simon,call_20240919_023.wav,27.0,33.0,PERSON,2026-03-24 21:10:34,NaN
4,Simon,call_20240919_023.wav,71.0,73.0,LOCATION,2026-03-24 21:08:57,NaN

In [3]:
df['Operator'].value_counts(dropna=False)

Operator
Simon      1546
Chris      1181
MUGERWA      70
Simon         4
Name: count, dtype: int64

In [5]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [7]:
# Normalize 'Operator' column: strip spaces and use title case
df['Operator'] = df['Operator'].str.strip().str.title()

# If you want to map specific variants:
# df['Operator'] = df['Operator'].replace({'MUGERWA': 'Mugerwa', 'SIMON': 'Simon'})

# Check the result
print(df['Operator'].value_counts(dropna=False))

Operator
Simon      1550
Chris      1181
Mugerwa      70
Name: count, dtype: int64

In [6]:
df['Audio File'].value_counts(dropna=False)

Audio File
call_20250328_003.wav                           233
call_20250312_003.wav                           160
call_20250415_006.wav                           113
call_20250318_003.wav                           108
call_20250123_001.wav                            84
call_20250424_003.wav                            79
call_20250228_003.wav                            75
call_20250106_001.wav                            72
call_20250219_002.wav                            71
call_20250107_006.wav                            70
call_20250114_002.wav                            66
call_20250217_003.wav                            64
call_20250305_002.wav                            63
call_20250207_001.wav                            61
call_20250327_003.wav                            58
call_20250317_005.wav                            53
call_20240930_001.wav                            50
call_20241112_004.wav                            47
call_20250429_006.wav                            46
call_20250429_007.wav                            44
call_20250327_001.wav                            42
call_20250409_002.wav                            40
call_20240925_001.wav                            39
call_20250213_002.wav                            39
call_20240924_001.wav                            36
call_20241003_002.wav                            35
call_20241115_001.wav                            33
call_20250203_001.wav                            32
call_20240927_002.wav                            29
call_20241212_005.wav                            28
call_20250213_001.wav                            28
call_20250304_003.wav                            26
call_20250303_010.wav                            26
call_20241021_006.wav                            25
call_20250116_004.wav                            24
call_20240920_001.wav                            24
call_20250109_008.wav                            23
call_20250128_016.wav                            22
call_20241218_003.wav                            21
call_20250115_008.wav                            21
call_20250220_005.wav                            21
call_20241126_003.wav                            20
call_20241105_004.wav                            20
call_20241017_012.wav                            20
call_20241001_004.wav                            20
call_20240923_001.wav                            20
call_20241111_005.wav                            20
call_20250429_005.wav                            18
call_20241003_003.wav                            18
call_20250127_001.wav                            17
call_20250101_001.wav                            17
call_20250325_002.wav                            16
call_20241106_006.wav                            16
call_20250217_001.wav                            16
call_20250214_001.wav                            15
call_20250101_002.wav                            15
call_20250505_002.wav                            15
call_20241111_006.wav                            15
call_20241001_013.wav                            14
call_20241004_002.wav                            12
call_20241204_001.wav                            12
call_20241227_004.wav                            12
call_20241127_002.wav                            12
call_20241104_001.wav                            11
call_20241113_009.wav                            11
call_20241014_003.wav                            10
call_20250207_004.wav                            10
call_20250127_004.wav                            10
call_20241218_007.wav                             9
call_20250312_001.wav                             9
call_20240919_023.wav                             9
call_20241002_004.wav                             9
call_20241025_002.wav                             9
call_20250305_001.wav                             8
call_20241105_003.wav                             6
call_20241231_001.wav                             6
call_20241025_001.wav                             6
call_20241205_001.wav                             6
call_20241011_001.wav                             6
call_20241111_008.wav                             6
call_20241223_002.wav                             6
call_20241031_009.wav                             5
call_20250103_001.wav                             5
call_20240924_002.wav                             4
call_20241218_009.wav                             4
call_20241212_003.wav                             4
call_20241218_006.wav                             4
call_20240924_003.wav                             4
call_20241017_007.wav                             4
call_20241010_003.wav                             4
call_20241008_009.wav                             3
call_20240923_006.wav                             3
call_20241218_002.wav                             3
call_20241220_002.wav                             3
WhatsApp Audio 2026-01-13 at 11.39.55 AM.mp3      3
call_20241118_005.wav                             3
call_20240923_005.wav                             2
call_20241114_003.wav                             2
call_20241106_004.wav                             2
call_20241015_002.wav                             1
Name: count, dtype: int64

In [8]:
df.head()

,Operator,Audio File,Start,Stop,Label,Timestamp,Comments
0,Simon,call_20240919_023.wav,71.0,73.0,LOCATION,2026-03-24 21:10:34,NaN
1,Simon,call_20240919_023.wav,67.0,69.0,LOCATION,2026-03-24 21:10:34,NaN
2,Simon,call_20240919_023.wav,55.0,60.0,LOCATION,2026-03-24 21:10:34,NaN
3,Simon,call_20240919_023.wav,27.0,33.0,PERSON,2026-03-24 21:10:34,NaN
4,Simon,call_20240919_023.wav,71.0,73.0,LOCATION,2026-03-24 21:08:57,NaN

In [9]:
# Get audio files annotated by Simon
simon_audios = set(df[df['Operator'] == 'Simon']['Audio File'])

# Get audio files annotated by Chris
chris_audios = set(df[df['Operator'] == 'Chris']['Audio File'])

# Find shared audio files
shared_audios = simon_audios & chris_audios

print("Audio files annotated by both Simon and Chris:")
print(shared_audios)

Audio files annotated by both Simon and Chris:
{'call_20250116_004.wav', 'call_20250123_001.wav', 'call_20250127_004.wav', 'call_20250207_004.wav', 'call_20250217_001.wav', 'call_20250424_003.wav', 'call_20250325_002.wav', 'call_20250228_003.wav', 'call_20250107_006.wav', 'call_20250312_003.wav', 'call_20250109_008.wav', 'call_20250328_003.wav', 'call_20250305_001.wav', 'call_20250115_008.wav', 'call_20250415_006.wav', 'call_20250220_005.wav', 'call_20250304_003.wav', 'call_20250429_006.wav', 'call_20250207_001.wav', 'call_20250312_001.wav', 'call_20250127_001.wav', 'call_20250106_001.wav', 'call_20250505_002.wav', 'call_20250327_003.wav', 'call_20250429_005.wav', 'call_20250128_016.wav', 'call_20250203_001.wav', 'call_20250327_001.wav', 'call_20250305_002.wav', 'call_20250219_002.wav', 'call_20250303_010.wav', 'call_20250213_001.wav', 'call_20250213_002.wav', 'call_20250214_001.wav', 'call_20250318_003.wav', 'call_20250114_002.wav', 'call_20250217_003.wav', 'call_20250409_002.wav', 'call_20250429_007.wav', 'call_20250317_005.wav'}

In [10]:
print("Number of shared audio files:", len(shared_audios))

Number of shared audio files: 40

In [11]:
# For each shared audio, show label counts and label types per operator
for audio in shared_audios:
    print(f"\nAudio File: {audio}")
    for operator in ['Simon', 'Chris']:
        op_df = df[(df['Audio File'] == audio) & (df['Operator'] == operator)]
        label_counts = op_df['Label'].value_counts()
        print(f"  Operator: {operator}")
        print(f"    Number of labels: {len(op_df)}")
        print(f"    Labels used: {list(label_counts.index)}")
        print(f"    Label counts:\n{label_counts.to_string()}")

Audio File: call_20250116_004.wav
  Operator: Simon
    Number of labels: 12
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    12
  Operator: Chris
    Number of labels: 12
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    12

Audio File: call_20250123_001.wav
  Operator: Simon
    Number of labels: 12
    Labels used: ['PERSON', 'USER_ID']
    Label counts:
Label
PERSON     9
USER_ID    3
  Operator: Chris
    Number of labels: 72
    Labels used: ['PERSON', 'USER_ID']
    Label counts:
Label
PERSON     60
USER_ID    12

Audio File: call_20250127_004.wav
  Operator: Simon
    Number of labels: 4
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    4
  Operator: Chris
    Number of labels: 6
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    6

Audio File: call_20250207_004.wav
  Operator: Simon
    Number of labels: 8
    Labels used: ['LOCATION']
    Label counts:
Label
LOCATION    8
  Operator: Chris
    Number of labels: 2
    Labels used: ['LOCATION']
    Label counts:
Label
LOCATION    2

Audio File: call_20250217_001.wav
  Operator: Simon
    Number of labels: 8
    Labels used: ['PERSON', 'LOCATION']
    Label counts:
Label
PERSON      4
LOCATION    4
  Operator: Chris
    Number of labels: 8
    Labels used: ['PERSON', 'LOCATION']
    Label counts:
Label
PERSON      4
LOCATION    4

Audio File: call_20250424_003.wav
  Operator: Simon
    Number of labels: 12
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    12
  Operator: Chris
    Number of labels: 67
    Labels used: ['PERSON', 'LOCATION']
    Label counts:
Label
PERSON      55
LOCATION    12

Audio File: call_20250325_002.wav
  Operator: Simon
    Number of labels: 8
    Labels used: ['LOCATION']
    Label counts:
Label
LOCATION    8
  Operator: Chris
    Number of labels: 8
    Labels used: ['LOCATION']
    Label counts:
Label
LOCATION    8

Audio File: call_20250228_003.wav
  Operator: Simon
    Number of labels: 45
    Labels used: ['PERSON', 'USER_ID']
    Label counts:
Label
PERSON     36
USER_ID     9
  Operator: Chris
    Number of labels: 30
    Labels used: ['PERSON', 'USER_ID']
    Label counts:
Label
PERSON     24
USER_ID     6

Audio File: call_20250107_006.wav
  Operator: Simon
    Number of labels: 4
    Labels used: ['PERSON', 'LOCATION']
    Label counts:
Label
PERSON      3
LOCATION    1
  Operator: Chris
    Number of labels: 66
    Labels used: ['PERSON', 'LOCATION']
    Label counts:
Label
PERSON      55
LOCATION    11

Audio File: call_20250312_003.wav
  Operator: Simon
    Number of labels: 29
    Labels used: ['LOCATION', 'PERSON']
    Label counts:
Label
LOCATION    23
PERSON       6
  Operator: Chris
    Number of labels: 131
    Labels used: ['LOCATION', 'PERSON']
    Label counts:
Label
LOCATION    109
PERSON       22

Audio File: call_20250109_008.wav
  Operator: Simon
    Number of labels: 8
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    8
  Operator: Chris
    Number of labels: 15
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    15

Audio File: call_20250328_003.wav
  Operator: Simon
    Number of labels: 72
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    72
  Operator: Chris
    Number of labels: 161
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    161

Audio File: call_20250305_001.wav
  Operator: Simon
    Number of labels: 2
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    2
  Operator: Chris
    Number of labels: 6
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    6

Audio File: call_20250115_008.wav
  Operator: Simon
    Number of labels: 12
    Labels used: ['LOCATION', 'PERSON']
    Label counts:
Label
LOCATION    6
PERSON      6
  Operator: Chris
    Number of labels: 9
    Labels used: ['LOCATION']
    Label counts:
Label
LOCATION    9

Audio File: call_20250415_006.wav
  Operator: Simon
    Number of labels: 78
    Labels used: ['LOCATION']
    Label counts:
Label
LOCATION    78
  Operator: Chris
    Number of labels: 35
    Labels used: ['LOCATION']
    Label counts:
Label
LOCATION    35

Audio File: call_20250220_005.wav
  Operator: Simon
    Number of labels: 6
    Labels used: ['PERSON', 'LOCATION']
    Label counts:
Label
PERSON      4
LOCATION    2
  Operator: Chris
    Number of labels: 15
    Labels used: ['PERSON', 'LOCATION']
    Label counts:
Label
PERSON      10
LOCATION     5

Audio File: call_20250304_003.wav
  Operator: Simon
    Number of labels: 3
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    3
  Operator: Chris
    Number of labels: 23
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    23

Audio File: call_20250429_006.wav
  Operator: Simon
    Number of labels: 16
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    16
  Operator: Chris
    Number of labels: 30
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    30

Audio File: call_20250207_001.wav
  Operator: Simon
    Number of labels: 35
    Labels used: ['LOCATION']
    Label counts:
Label
LOCATION    35
  Operator: Chris
    Number of labels: 26
    Labels used: ['LOCATION']
    Label counts:
Label
LOCATION    26

Audio File: call_20250312_001.wav
  Operator: Simon
    Number of labels: 3
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    3
  Operator: Chris
    Number of labels: 6
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    6

Audio File: call_20250127_001.wav
  Operator: Simon
    Number of labels: 7
    Labels used: ['USER_ID']
    Label counts:
Label
USER_ID    7
  Operator: Chris
    Number of labels: 10
    Labels used: ['USER_ID']
    Label counts:
Label
USER_ID    10

Audio File: call_20250106_001.wav
  Operator: Simon
    Number of labels: 30
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    30
  Operator: Chris
    Number of labels: 42
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    42

Audio File: call_20250505_002.wav
  Operator: Simon
    Number of labels: 9
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    9
  Operator: Chris
    Number of labels: 6
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    6

Audio File: call_20250327_003.wav
  Operator: Simon
    Number of labels: 34
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    34
  Operator: Chris
    Number of labels: 24
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    24

Audio File: call_20250429_005.wav
  Operator: Simon
    Number of labels: 6
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    6
  Operator: Chris
    Number of labels: 12
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    12

Audio File: call_20250128_016.wav
  Operator: Simon
    Number of labels: 10
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    10
  Operator: Chris
    Number of labels: 12
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    12

Audio File: call_20250203_001.wav
  Operator: Simon
    Number of labels: 20
    Labels used: ['PERSON', 'LOCATION']
    Label counts:
Label
PERSON      15
LOCATION     5
  Operator: Chris
    Number of labels: 12
    Labels used: ['PERSON', 'LOCATION']
    Label counts:
Label
PERSON      9
LOCATION    3

Audio File: call_20250327_001.wav
  Operator: Simon
    Number of labels: 26
    Labels used: ['PERSON', 'LOCATION']
    Label counts:
Label
PERSON      14
LOCATION    12
  Operator: Chris
    Number of labels: 16
    Labels used: ['LOCATION', 'PERSON']
    Label counts:
Label
LOCATION    8
PERSON      8

Audio File: call_20250305_002.wav
  Operator: Simon
    Number of labels: 22
    Labels used: ['LOCATION', 'PERSON']
    Label counts:
Label
LOCATION    17
PERSON       5
  Operator: Chris
    Number of labels: 41
    Labels used: ['PERSON', 'LOCATION']
    Label counts:
Label
PERSON      29
LOCATION    12

Audio File: call_20250219_002.wav
  Operator: Simon
    Number of labels: 16
    Labels used: ['LOCATION', 'PERSON']
    Label counts:
Label
LOCATION    10
PERSON       6
  Operator: Chris
    Number of labels: 55
    Labels used: ['LOCATION', 'PERSON']
    Label counts:
Label
LOCATION    33
PERSON      22

Audio File: call_20250303_010.wav
  Operator: Simon
    Number of labels: 10
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    10
  Operator: Chris
    Number of labels: 16
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    16

Audio File: call_20250213_001.wav
  Operator: Simon
    Number of labels: 6
    Labels used: ['PERSON', 'LOCATION']
    Label counts:
Label
PERSON      4
LOCATION    2
  Operator: Chris
    Number of labels: 22
    Labels used: ['PERSON', 'LOCATION']
    Label counts:
Label
PERSON      18
LOCATION     4

Audio File: call_20250213_002.wav
  Operator: Simon
    Number of labels: 15
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    15
  Operator: Chris
    Number of labels: 24
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    24

Audio File: call_20250214_001.wav
  Operator: Simon
    Number of labels: 6
    Labels used: ['PERSON', 'LOCATION']
    Label counts:
Label
PERSON      4
LOCATION    2
  Operator: Chris
    Number of labels: 9
    Labels used: ['PERSON', 'LOCATION']
    Label counts:
Label
PERSON      6
LOCATION    3

Audio File: call_20250318_003.wav
  Operator: Simon
    Number of labels: 54
    Labels used: ['PERSON', 'LOCATION', 'USER_ID']
    Label counts:
Label
PERSON      36
LOCATION    12
USER_ID      6
  Operator: Chris
    Number of labels: 54
    Labels used: ['PERSON', 'LOCATION', 'USER_ID']
    Label counts:
Label
PERSON      36
LOCATION    12
USER_ID      6

Audio File: call_20250114_002.wav
  Operator: Simon
    Number of labels: 54
    Labels used: ['PERSON', 'LOCATION']
    Label counts:
Label
PERSON      36
LOCATION    18
  Operator: Chris
    Number of labels: 12
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    12

Audio File: call_20250217_003.wav
  Operator: Simon
    Number of labels: 24
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    24
  Operator: Chris
    Number of labels: 40
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    40

Audio File: call_20250409_002.wav
  Operator: Simon
    Number of labels: 25
    Labels used: ['PERSON', 'LOCATION']
    Label counts:
Label
PERSON      15
LOCATION    10
  Operator: Chris
    Number of labels: 15
    Labels used: ['PERSON', 'LOCATION']
    Label counts:
Label
PERSON      9
LOCATION    6

Audio File: call_20250429_007.wav
  Operator: Simon
    Number of labels: 30
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    30
  Operator: Chris
    Number of labels: 14
    Labels used: ['PERSON']
    Label counts:
Label
PERSON    14

Audio File: call_20250317_005.wav
  Operator: Simon
    Number of labels: 36
    Labels used: ['LOCATION']
    Label counts:
Label
LOCATION    36
  Operator: Chris
    Number of labels: 17
    Labels used: ['LOCATION']
    Label counts:
Label
LOCATION    17

In [12]:
from collections import defaultdict

for audio in shared_audios:
    print(f"\nAudio File: {audio}")
    simon_df = df[(df['Audio File'] == audio) & (df['Operator'] == 'Simon')]
    chris_df = df[(df['Audio File'] == audio) & (df['Operator'] == 'Chris')]
    all_labels = set(simon_df['Label']).union(set(chris_df['Label']))
    for label in all_labels:
        simon_spans = set(zip(
            simon_df[simon_df['Label'] == label]['Start'],
            simon_df[simon_df['Label'] == label]['Stop']
        ))
        chris_spans = set(zip(
            chris_df[chris_df['Label'] == label]['Start'],
            chris_df[chris_df['Label'] == label]['Stop']
        ))
        matches = simon_spans & chris_spans
        simon_only = simon_spans - chris_spans
        chris_only = chris_spans - simon_spans
        print(f"  Label: {label}")
        print(f"    Exact matches: {len(matches)}")
        print(f"    Simon only: {len(simon_only)}")
        print(f"    Chris only: {len(chris_only)}")
        if simon_only:
            print(f"      Simon only spans: {simon_only}")
        if chris_only:
            print(f"      Chris only spans: {chris_only}")

Audio File: call_20250116_004.wav
  Label: PERSON
    Exact matches: 0
    Simon only: 6
    Chris only: 10
      Simon only spans: {(91.0, 94.0), (31.0, 32.0), (24.6, 26.0), (24.9, 26.0), (24.965, 26.0), (25.0, 26.0)}
      Chris only spans: {(25.1, 25.7), (31.2, 31.9), (91.7, 94.8), (25.0, 25.7), (92.5, 95.0), (31.35, 31.9), (31.5, 32.3), (25.5, 26.3), (31.45, 31.9), (25.2, 25.7)}

Audio File: call_20250123_001.wav
  Label: USER_ID
    Exact matches: 1
    Simon only: 1
    Chris only: 1
      Simon only spans: {(228.7, 244.0)}
      Chris only spans: {(229.4, 244.0)}
  Label: PERSON
    Exact matches: 0
    Simon only: 5
    Chris only: 17
      Simon only spans: {(64.5, 68.0), (58.0, 59.0), (64.0, 68.0), (84.0, 86.5), (84.0, 86.0)}
      Chris only spans: {(64.5, 65.0), (67.4, 68.0), (64.3, 65.0), (67.3, 68.0), (84.6, 85.7), (67.9, 68.3), (64.8, 65.3), (84.8, 85.7), (58.5, 59.3), (66.1, 66.5), (58.2, 59.0), (84.6, 85.5), (66.5, 66.9), (84.6, 85.6), (66.0, 66.4), (85.3, 86.3), (66.2, 66.5)}

Audio File: call_20250127_004.wav
  Label: PERSON
    Exact matches: 0
    Simon only: 3
    Chris only: 4
      Simon only spans: {(103.0, 104.0), (109.0, 110.0), (108.6, 110.0)}
      Chris only spans: {(108.9, 110.0), (103.0, 104.2), (108.6, 109.8), (103.3, 104.5)}

Audio File: call_20250207_004.wav
  Label: LOCATION
    Exact matches: 0
    Simon only: 4
    Chris only: 2
      Simon only spans: {(290.0, 295.0), (296.0, 300.0), (225.0, 228.0), (276.0, 278.0)}
      Chris only spans: {(225.7, 228.0), (225.1, 227.7)}

Audio File: call_20250217_001.wav
  Label: PERSON
    Exact matches: 0
    Simon only: 4
    Chris only: 4
      Simon only spans: {(45.3, 47.0), (45.5, 47.0), (45.0, 46.0), (45.2, 47.0)}
      Chris only spans: {(44.9, 46.0), (45.2, 46.4), (45.3, 46.4), (45.0, 46.2)}
  Label: LOCATION
    Exact matches: 0
    Simon only: 1
    Chris only: 2
      Simon only spans: {(42.0, 43.0)}
      Chris only spans: {(42.5, 43.4), (42.0, 43.2)}

Audio File: call_20250424_003.wav
  Label: PERSON
    Exact matches: 0
    Simon only: 7
    Chris only: 24
      Simon only spans: {(55.0, 56.0), (31.8, 33.0), (32.0, 33.0), (24.8, 26.5), (24.8, 26.0), (22.0, 23.8), (25.0, 26.0)}
      Chris only spans: {(32.2, 33.0), (54.5, 55.3), (22.6, 23.3), (55.5, 56.3), (31.0, 32.0), (229.75, 230.4), (24.8, 26.2), (55.25, 55.8), (22.9, 23.6), (229.0, 230.0), (34.2, 35.0), (31.4, 32.0), (31.7, 32.45), (23.6, 24.2), (229.8, 230.4), (230.0, 231.0), (229.7, 230.4), (54.0, 54.8), (31.7, 32.3), (23.0, 23.6), (55.0, 55.8), (24.7, 26.2), (55.1, 55.6), (55.3, 55.8)}
  Label: LOCATION
    Exact matches: 0
    Simon only: 0
    Chris only: 5
      Chris only spans: {(328.8, 329.3), (328.2, 329.0), (329.6, 330.2), (329.2, 330.0), (328.9, 329.4)}

Audio File: call_20250325_002.wav
  Label: LOCATION
    Exact matches: 0
    Simon only: 4
    Chris only: 7
      Simon only spans: {(114.0, 116.0), (116.0, 123.0), (116.5, 123.0), (117.0, 123.0)}
      Chris only spans: {(114.25, 115.7), (114.4, 115.7), (120.0, 122.0), (118.5, 119.1), (120.0, 120.2), (116.2, 117.8), (118.0, 118.5)}

Audio File: call_20250228_003.wav
  Label: USER_ID
    Exact matches: 1
    Simon only: 0
    Chris only: 2
      Chris only spans: {(192.0, 202.2), (192.0, 202.8)}
  Label: PERSON
    Exact matches: 3
    Simon only: 9
    Chris only: 13
      Simon only spans: {(218.8, 221.0), (204.6, 206.0), (63.0, 63.6), (64.0, 65.0), (219.3, 221.0), (218.6, 221.0), (62.5, 63.0), (62.0, 63.0), (219.0, 221.0)}
      Chris only spans: {(62.4, 62.8), (64.6, 65.0), (219.0, 220.6), (62.3, 62.75), (219.3, 220.6), (204.0, 205.5), (62.3, 62.8), (64.0, 64.5), (62.0, 62.7), (62.3, 62.7), (62.8, 63.4), (64.2, 64.8), (219.2, 220.6)}

Audio File: call_20250107_006.wav
  Label: PERSON
    Exact matches: 1
    Simon only: 2
    Chris only: 27
      Simon only spans: {(39.0, 40.0), (47.0, 50.0)}
      Chris only spans: {(39.1, 39.9), (48.5, 49.0), (47.4, 47.8), (44.3, 45.0), (48.7, 49.7), (48.7, 49.2), (39.2, 39.8), (39.0, 39.5), (41.6, 42.2), (47.8, 48.3), (49.0, 50.0), (39.0, 39.9), (41.15, 41.6), (47.3, 47.8), (39.0, 39.8), (41.6, 42.0), (48.9, 49.7), (43.75, 44.1), (49.35, 50.0), (47.35, 47.8), (41.3, 42.0), (49.5, 50.0), (44.1, 44.8), (42.0, 42.6), (41.8, 42.2), (49.25, 50.0), (47.5, 48.3)}
  Label: LOCATION
    Exact matches: 0
    Simon only: 1
    Chris only: 2
      Simon only spans: {(117.0, 119.0)}
      Chris only spans: {(116.5, 117.3), (117.0, 118.0)}

Audio File: call_20250312_003.wav
  Label: PERSON
    Exact matches: 0
    Simon only: 3
    Chris only: 6
      Simon only spans: {(22.0, 24.0), (23.0, 23.9), (27.0, 28.0)}
      Chris only spans: {(27.2, 28.0), (23.0, 24.0), (23.15, 24.0), (23.25, 24.0), (27.25, 28.0), (27.6, 28.3)}
  Label: LOCATION
    Exact matches: 1
    Simon only: 14
    Chris only: 40
      Simon only spans: {(66.0, 68.0), (58.0, 59.0), (64.0, 68.0), (48.0, 52.0), (69.0, 71.0), (61.0, 64.0), (46.0, 47.0), (75.0, 79.0), (69.0, 70.0), (48.0, 51.0), (62.0, 63.0), (60.0, 64.0), (74.0, 82.0), (216.0, 217.0)}
      Chris only spans: {(75.0, 76.3), (46.2, 47.1), (65.9, 67.2), (216.6, 217.2), (81.3, 82.0), (76.9, 79.5), (46.5, 47.4), (75.4, 76.3), (69.5, 70.3), (51.2, 52.0), (75.25, 76.3), (77.1, 79.5), (50.9, 51.7), (75.1, 76.3), (46.15, 47.1), (76.75, 79.0), (76.75, 79.25), (58.1, 59.0), (76.75, 79.5), (80.9, 82.0), (65.7, 67.2), (75.0, 75.85), (48.2, 49.1), (75.0, 75.6), (48.2, 49.0), (50.7, 51.6), (69.4, 70.2), (66.3, 68.0), (58.1, 58.7), (48.5, 49.4), (58.2, 59.0), (69.6, 70.3), (69.4, 70.3), (66.0, 67.2), (58.5, 59.3), (75.0, 76.0), (65.8, 67.2), (50.8, 51.7), (77.3, 79.5), (216.75, 217.3)}

Audio File: call_20250109_008.wav
  Label: PERSON
    Exact matches: 0
    Simon only: 5
    Chris only: 10
      Simon only spans: {(25.5, 28.0), (25.5, 28.2), (30.0, 31.0), (26.0, 28.0), (25.0, 26.0)}
      Chris only spans: {(27.6, 28.2), (25.7, 26.3), (25.3, 26.3), (30.0, 30.7), (28.0, 28.6), (30.25, 31.0), (30.3, 31.0), (30.7, 31.3), (27.5, 28.2), (25.5, 26.3)}

Audio File: call_20250328_003.wav
  Label: PERSON
    Exact matches: 1
    Simon only: 17
    Chris only: 46
      Simon only spans: {(168.9, 171.0), (163.9, 165.0), (169.2, 171.0), (173.0, 174.0), (169.0, 171.0), (34.0, 35.0), (164.0, 165.0), (111.4, 115.0), (22.0, 23.0), (111.0, 115.0), (140.0, 141.0), (149.0, 150.0), (168.0, 170.0), (46.0, 47.0), (81.0, 83.0), (23.0, 24.0), (135.0, 137.0)}
      Chris only spans: {(168.8, 169.2), (170.6, 171.2), (22.4, 22.9), (169.7, 171.8), (34.5, 36.0), (172.8, 173.4), (168.65, 169.2), (168.65, 169.3), (148.8, 149.5), (164.2, 164.9), (112.5, 114.0), (169.8, 170.2), (23.4, 23.9), (135.9, 136.8), (26.0, 26.6), (112.5, 114.3), (171.6, 172.2), (148.9, 149.9), (164.4, 165.0), (164.8, 165.4), (114.4, 115.0), (36.3, 37.0), (139.3, 140.0), (46.3, 47.0), (149.0, 149.6), (36.0, 36.7), (22.7, 23.3), (81.5, 82.2), (149.3, 150.0), (139.9, 140.5), (174.5, 175.0), (114.7, 115.3), (135.5, 136.35), (135.5, 136.1), (140.1, 140.5), (140.3, 141.0), (34.0, 35.2), (173.2, 173.8), (23.7, 24.3), (37.0, 37.7), (149.2, 150.0), (82.0, 82.8), (34.0, 35.5), (164.2, 164.8), (46.7, 47.3), (35.0, 36.2)}

Audio File: call_20250305_001.wav
  Label: PERSON
    Exact matches: 0
    Simon only: 2
    Chris only: 5
      Simon only spans: {(29.8, 31.0), (30.0, 31.0)}
      Chris only spans: {(30.5, 32.0), (29.7, 31.3), (29.75, 31.3), (30.0, 31.5), (29.85, 31.3)}

Audio File: call_20250115_008.wav
  Label: PERSON
    Exact matches: 0
    Simon only: 1
    Chris only: 0
      Simon only spans: {(38.0, 39.0)}
  Label: LOCATION
    Exact matches: 0
    Simon only: 4
    Chris only: 7
      Simon only spans: {(51.0, 55.8), (51.0, 55.0), (49.8, 55.8), (51.4, 55.8)}
      Chris only spans: {(52.4, 54.0), (50.7, 51.1), (51.1, 51.7), (50.7, 51.25), (54.9, 55.4), (52.65, 54.0), (55.2, 55.8)}

Audio File: call_20250415_006.wav
  Label: LOCATION
    Exact matches: 0
    Simon only: 21
    Chris only: 14
      Simon only spans: {(122.0, 123.8), (118.0, 119.0), (123.0, 124.0), (124.0, 125.9), (142.8, 143.7), (138.5, 138.9), (142.7, 143.7), (137.1, 138.9), (126.0, 128.0), (143.2, 143.7), (122.0, 1238.0), (142.0, 143.0), (122.1, 123.8), (122.7, 123.8), (138.0, 138.9), (137.5, 138.9), (125.0, 125.9), (122.8, 123.8), (142.0, 143.7), (137.2, 138.9), (143.5, 143.7)}
      Chris only spans: {(138.1, 138.7), (126.9, 128.7), (138.2, 138.7), (137.5, 138.3), (138.0, 138.5), (124.45, 125.1), (124.8, 125.4), (124.45, 125.0), (118.2, 119.2), (117.7, 118.8), (142.5, 143.3), (122.5, 123.2), (117.6, 118.8), (117.5, 118.8)}

Audio File: call_20250220_005.wav
  Label: PERSON
    Exact matches: 0
    Simon only: 3
    Chris only: 7
      Simon only spans: {(136.0, 138.0), (133.0, 134.0), (132.8, 134.0)}
      Chris only spans: {(135.8, 137.8), (133.3, 134.3), (135.8, 136.5), (136.5, 138.0), (132.9, 133.6), (132.8, 133.6), (132.8, 133.5)}
  Label: LOCATION
    Exact matches: 0
    Simon only: 2
    Chris only: 3
      Simon only spans: {(298.0, 299.0), (298.0, 300.0)}
      Chris only spans: {(298.1, 300.2), (298.1, 299.0), (299.1, 300.0)}

Audio File: call_20250304_003.wav
  Label: PERSON
    Exact matches: 0
    Simon only: 3
    Chris only: 12
      Simon only spans: {(63.0, 64.0), (69.0, 70.0), (73.0, 74.0)}
      Chris only spans: {(73.0, 73.7), (62.8, 63.6), (73.3, 73.9), (73.0, 73.6), (73.1, 73.7), (73.2, 73.9), (62.9, 63.6), (73.0, 73.5), (69.25, 69.9), (63.2, 63.9), (69.2, 69.9), (62.9, 63.5)}

Audio File: call_20250429_006.wav
  Label: PERSON
    Exact matches: 0
    Simon only: 9
    Chris only: 12
      Simon only spans: {(249.6, 251.0), (31.0, 33.0), (32.0, 33.0), (21.0, 22.0), (31.0, 32.0), (253.0, 253.9), (252.6, 253.9), (20.0, 22.0), (250.0, 251.0)}
      Chris only spans: {(253.3, 254.1), (245.5, 246.3), (249.5, 251.0), (255.5, 256.0), (244.8, 245.5), (244.7, 245.3), (252.1, 254.1), (255.3, 256.0), (31.4, 33.0), (31.3, 33.0), (20.8, 22.3), (31.7, 33.0)}

Audio File: call_20250207_001.wav
  Label: LOCATION
    Exact matches: 0
    Simon only: 11
    Chris only: 18
      Simon only spans: {(350.0, 351.0), (346.0, 348.0), (354.6, 357.0), (355.0, 356.0), (365.0, 366.0), (354.6, 356.5), (341.0, 343.0), (354.6, 356.0), (342.0, 343.0), (324.0, 326.0), (364.6, 366.0)}
      Chris only spans: {(350.0, 350.5), (341.6, 342.5), (354.8, 356.35), (365.5, 366.2), (324.2, 324.8), (346.75, 347.3), (325.85, 326.3), (346.7, 347.3), (355.0, 356.6), (350.5, 351.2), (349.9, 350.5), (341.5, 342.5), (354.7, 356.35), (347.0, 347.6), (324.2, 326.4), (326.2, 326.7), (366.0, 366.6), (324.7, 325.4)}

Audio File: call_20250312_001.wav
  Label: PERSON
    Exact matches: 1
    Simon only: 1
    Chris only: 4
      Simon only spans: {(24.0, 25.0)}
      Chris only spans: {(24.3, 25.1), (24.0, 24.5), (38.3, 39.3), (23.9, 245.0)}

Audio File: call_20250127_001.wav
  Label: USER_ID
    Exact matches: 0
    Simon only: 4
    Chris only: 4
      Simon only spans: {(102.0, 122.0), (125.0, 136.0), (107.0, 136.0), (124.0, 136.0)}
      Chris only spans: {(124.8, 137.0), (125.0, 137.0), (103.0, 122.9), (124.65, 137.0)}

Audio File: call_20250106_001.wav
  Label: PERSON
    Exact matches: 0
    Simon only: 10
    Chris only: 20
      Simon only spans: {(28.6, 30.0), (118.0, 120.0), (28.1, 30.0), (26.0, 27.0), (32.0, 33.0), (28.2, 30.0), (27.5, 28.0), (25.0, 27.0), (78.0, 79.0), (29.0, 30.0)}
      Chris only spans: {(119.8, 120.2), (78.5, 79.0), (29.7, 30.4), (78.5, 79.3), (32.3, 33.0), (117.7, 118.3), (28.2, 28.8), (119.0, 119.7), (28.2, 28.7), (118.7, 119.3), (118.4, 118.75), (119.3, 119.7), (32.4, 33.0), (25.5, 26.7), (119.0, 129.7), (29.3, 30.0), (119.4, 119.7), (25.6, 26.7), (78.5, 79.15), (28.4, 29.2)}

Audio File: call_20250505_002.wav
  Label: PERSON
    Exact matches: 0
    Simon only: 7
    Chris only: 6
      Simon only spans: {(29.9, 31.0), (30.6, 31.0), (30.4, 31.0), (30.1, 31.0), (29.5, 31.0), (30.2, 31.0), (30.0, 31.0)}
      Chris only spans: {(72.0, 73.0), (30.2, 30.7), (72.5, 73.3), (72.5, 74.0), (30.5, 31.2), (29.7, 30.5)}

Audio File: call_20250327_003.wav
  Label: PERSON
    Exact matches: 0
    Simon only: 7
    Chris only: 11
      Simon only spans: {(65.0, 66.0), (39.0, 40.0), (43.5, 44.0), (40.0, 41.0), (39.8, 40.0), (46.0, 47.0), (43.0, 44.0)}
      Chris only spans: {(39.0, 39.7), (43.6, 44.4), (43.3, 43.8), (43.2, 43.7), (39.7, 40.5), (43.2, 43.8), (43.0, 43.4), (65.3, 65.8), (39.45, 40.0), (43.4, 43.8), (46.6, 47.3)}

Audio File: call_20250429_005.wav
  Label: PERSON
    Exact matches: 1
    Simon only: 3
    Chris only: 6
      Simon only spans: {(66.0, 67.0), (63.0, 63.9), (62.0, 63.0)}
      Chris only spans: {(62.7, 63.3), (68.1, 69.0), (63.5, 64.3), (62.8, 63.35), (62.9, 63.45), (65.8, 67.2)}

Audio File: call_20250128_016.wav
  Label: PERSON
    Exact matches: 0
    Simon only: 8
    Chris only: 7
      Simon only spans: {(29.5, 30.2), (33.6, 34.5), (34.0, 35.0), (33.5, 34.5), (28.5, 30.0), (29.5, 30.0), (33.3, 34.5), (29.0, 30.0)}
      Chris only spans: {(37.2, 37.8), (29.4, 30.0), (33.3, 34.6), (29.7, 30.3), (33.7, 34.9), (37.6, 38.0), (37.0, 37.4)}

Audio File: call_20250203_001.wav
  Label: PERSON
    Exact matches: 0
    Simon only: 4
    Chris only: 8
      Simon only spans: {(24.0, 25.0), (21.0, 22.0), (27.0, 29.0), (20.0, 21.0)}
      Chris only spans: {(24.7, 25.3), (24.3, 24.9), (27.5, 29.0), (21.7, 22.3), (27.7, 29.2), (21.2, 22.0), (24.0, 24.6), (27.3, 29.0)}
  Label: LOCATION
    Exact matches: 0
    Simon only: 4
    Chris only: 3
      Simon only spans: {(143.0, 145.2), (143.0, 145.0), (144.0, 146.0), (145.0, 146.0)}
      Chris only spans: {(144.8, 145.7), (144.2, 145.2), (144.3, 145.2)}

Audio File: call_20250327_001.wav
  Label: PERSON
    Exact matches: 1
    Simon only: 4
    Chris only: 3
      Simon only spans: {(94.8, 96.0), (92.0, 93.0), (92.5, 93.0), (92.8, 93.0)}
      Chris only spans: {(94.5, 95.3), (92.25, 93.3), (92.5, 93.5)}
  Label: LOCATION
    Exact matches: 0
    Simon only: 4
    Chris only: 6
      Simon only spans: {(125.0, 126.0), (122.0, 123.0), (125.1, 126.0), (124.8, 126.0)}
      Chris only spans: {(121.9, 122.5), (125.8, 126.8), (125.7, 128.3), (122.1, 123.0), (125.0, 125.8), (121.9, 122.85)}

Audio File: call_20250305_002.wav
  Label: PERSON
    Exact matches: 1
    Simon only: 0
    Chris only: 12
      Chris only spans: {(446.75, 447.7), (441.4, 442.0), (441.3, 442.0), (439.4, 440.4), (439.2, 440.0), (441.7, 442.4), (447.6, 448.3), (436.6, 437.2), (448.5, 449.3), (435.6, 446.2), (446.6, 447.3), (436.2, 436.9)}
  Label: LOCATION
    Exact matches: 0
    Simon only: 8
    Chris only: 6
      Simon only spans: {(150.0, 152.0), (152.5, 155.0), (152.5, 155.8), (152.5, 156.0), (153.0, 153.8), (155.0, 156.0), (152.8, 154.0), (161.0, 162.0)}
      Chris only spans: {(150.1, 152.9), (154.75, 155.4), (154.75, 155.65), (150.0, 152.9), (150.4, 153.0), (155.0, 155.8)}

Audio File: call_20250219_002.wav
  Label: PERSON
    Exact matches: 0
    Simon only: 3
    Chris only: 9
      Simon only spans: {(157.0, 160.0), (156.8, 160.0), (158.0, 159.0)}
      Chris only spans: {(157.1, 158.0), (158.5, 159.0), (159.0, 160.0), (158.5, 159.1), (157.1, 157.6), (157.4, 158.2), (157.4, 1582.0), (157.1, 157.5), (158.6, 159.1)}
  Label: LOCATION
    Exact matches: 0
    Simon only: 5
    Chris only: 16
      Simon only spans: {(161.0, 161.8), (160.1, 161.0), (161.6, 162.6), (162.0, 163.0), (160.5, 161.0)}
      Chris only spans: {(158.0, 158.3), (157.75, 158.0), (162.0, 162.4), (160.5, 160.85), (160.5, 160.75), (160.5, 160.8), (160.4, 160.75), (157.8, 158.1), (162.6, 163.0), (161.6, 162.0), (161.9, 162.3), (157.65, 158.0), (160.35, 160.8), (160.75, 161.3), (162.05, 162.4), (158.5, 158.9)}

Audio File: call_20250303_010.wav
  Label: PERSON
    Exact matches: 0
    Simon only: 6
    Chris only: 9
      Simon only spans: {(60.8, 61.0), (58.0, 59.0), (59.9, 61.0), (60.5, 61.5), (60.0, 61.0), (59.8, 60.8)}
      Chris only spans: {(60.5, 61.2), (60.5, 61.7), (58.5, 60.2), (60.5, 61.1), (57.9, 58.6), (60.5, 61.0), (57.5, 58.2), (60.5, 61.15), (60.5, 61.4)}

Audio File: call_20250213_001.wav
  Label: PERSON
    Exact matches: 0
    Simon only: 3
    Chris only: 13
      Simon only spans: {(30.0, 32.0), (34.0, 35.0), (31.0, 32.0)}
      Chris only spans: {(30.6, 31.5), (30.6, 31.0), (30.6, 31.8), (30.6, 30.9), (35.0, 35.5), (30.7, 31.8), (34.65, 35.0), (35.1, 35.6), (34.5, 35.0), (30.6, 31.1), (34.8, 35.2), (31.0, 31.5), (34.7, 35.2)}
  Label: LOCATION
    Exact matches: 0
    Simon only: 2
    Chris only: 4
      Simon only spans: {(92.5, 96.0), (93.0, 95.0)}
      Chris only spans: {(31.2, 31.55), (31.5, 31.9), (31.3, 31.9), (31.8, 32.3)}

Audio File: call_20250213_002.wav
  Label: PERSON
    Exact matches: 0
    Simon only: 11
    Chris only: 15
      Simon only spans: {(22.0, 27.0), (26.0, 27.0), (22.0, 23.0), (24.0, 25.0), (22.0, 26.0), (27.5, 28.0), (25.0, 27.0), (22.0, 25.0), (26.5, 27.0), (27.0, 28.0), (22.0, 28.0)}
      Chris only spans: {(27.2, 28.0), (24.8, 25.2), (23.6, 24.0), (26.6, 27.5), (25.5, 25.8), (26.6, 27.2), (22.2, 22.6), (25.8, 26.1), (26.0, 26.4), (26.8, 27.5), (23.3, 23.8), (22.6, 23.2), (23.9, 24.3), (25.0, 26.0), (26.3, 27.2)}

Audio File: call_20250214_001.wav
  Label: PERSON
    Exact matches: 0
    Simon only: 3
    Chris only: 5
      Simon only spans: {(45.0, 46.0), (41.0, 43.0), (44.8, 45.9)}
      Chris only spans: {(45.4, 45.9), (44.8, 45.25), (44.7, 45.1), (41.75, 43.0), (41.3, 42.7)}
  Label: LOCATION
    Exact matches: 0
    Simon only: 1
    Chris only: 3
      Simon only spans: {(54.0, 55.0)}
      Chris only spans: {(54.0, 54.5), (53.9, 54.3), (54.5, 55.0)}

Audio File: call_20250318_003.wav
  Label: LOCATION
    Exact matches: 0
    Simon only: 2
    Chris only: 6
      Simon only spans: {(300.0, 303.0), (204.0, 206.0)}
      Chris only spans: {(300.0, 302.7), (204.15, 206.3), (204.25, 206.3), (204.2, 206.3), (299.8, 302.5), (299.85, 302.5)}
  Label: USER_ID
    Exact matches: 0
    Simon only: 1
    Chris only: 3
      Simon only spans: {(420.0, 435.0)}
      Chris only spans: {(420.5, 435.5), (420.4, 435.5), (420.7, 435.5)}
  Label: PERSON
    Exact matches: 1
    Simon only: 14
    Chris only: 16
      Simon only spans: {(382.0, 384.0), (201.0, 202.0), (436.0, 438.0), (383.0, 385.0), (213.0, 215.0), (210.0, 212.0), (211.0, 212.0), (200.2, 202.0), (200.0, 202.0), (382.7, 388.0), (382.5, 388.0), (385.0, 388.0), (386.0, 388.0), (362.0, 364.0)}
      Chris only spans: {(382.7, 384.1), (200.0, 201.5), (436.45, 438.0), (386.0, 387.8), (213.5, 214.2), (210.7, 212.0), (436.4, 438.0), (436.6, 438.0), (210.7, 212.1), (200.15, 201.5), (386.1, 387.8), (382.8, 384.1), (436.8, 438.0), (211.0, 212.3), (383.0, 384.3), (386.4, 388.0)}

Audio File: call_20250114_002.wav
  Label: PERSON
    Exact matches: 0
    Simon only: 20
    Chris only: 12
      Simon only spans: {(22.001, 24.22), (21.0, 22.0), (22.15, 24.22), (24.0, 26.0), (21.8, 24.22), (22.3, 24.22), (21.945, 24.22), (23.8, 26.0), (21.994, 24.22), (21.95, 24.22), (22.0, 22.5), (21.999, 24.22), (24.42, 26.0), (21.8, 22.5), (21.5, 22.5), (23.0, 26.0), (21.0, 24.22), (22.002, 24.22), (23.6, 26.0), (21.8, 22.42)}
      Chris only spans: {(21.5, 22.0), (23.8, 24.1), (22.5, 23.0), (21.75, 22.2), (24.5, 25.5), (24.4, 24.7), (23.65, 23.9), (23.4, 23.7), (21.8, 22.4), (25.1, 26.5), (24.1, 25.5), (24.6, 25.7)}
  Label: LOCATION
    Exact matches: 0
    Simon only: 11
    Chris only: 0
      Simon only spans: {(31.994, 33.0), (31.0, 33.0), (32.0, 33.0), (31.99, 33.0), (32.3, 33.0), (32.002, 33.0), (31.6, 33.0), (31.9, 33.0), (32.15, 33.0), (31.999, 33.0), (31.95, 33.0)}

Audio File: call_20250217_003.wav
  Label: PERSON
    Exact matches: 1
    Simon only: 8
    Chris only: 12
      Simon only spans: {(68.8, 70.0), (65.0, 66.0), (68.7, 70.0), (68.96, 70.0), (77.0, 78.0), (68.4, 70.0), (68.0, 70.0), (71.0, 72.0)}

In [13]:
summary = []
for audio in shared_audios:
    simon_df = df[(df['Audio File'] == audio) & (df['Operator'] == 'Simon')]
    chris_df = df[(df['Audio File'] == audio) & (df['Operator'] == 'Chris')]
    summary.append({
        "Audio File": audio,
        "Simon Count": len(simon_df),
        "Chris Count": len(chris_df),
        "Simon Labels": set(simon_df['Label']),
        "Chris Labels": set(chris_df['Label'])
    })
summary_df = pd.DataFrame(summary)
display(summary_df)

,Audio File,Simon Count,Chris Count,Simon Labels,Chris Labels
0,call_20250116_004.wav,12,12,{PERSON},{PERSON}
1,call_20250123_001.wav,12,72,"{USER_ID, PERSON}","{USER_ID, PERSON}"
2,call_20250127_004.wav,4,6,{PERSON},{PERSON}
3,call_20250207_004.wav,8,2,{LOCATION},{LOCATION}
4,call_20250217_001.wav,8,8,"{PERSON, LOCATION}","{PERSON, LOCATION}"
5,call_20250424_003.wav,12,67,{PERSON},"{PERSON, LOCATION}"
6,call_20250325_002.wav,8,8,{LOCATION},{LOCATION}
7,call_20250228_003.wav,45,30,"{USER_ID, PERSON}","{USER_ID, PERSON}"
8,call_20250107_006.wav,4,66,"{PERSON, LOCATION}","{PERSON, LOCATION}"
9,call_20250312_003.wav,29,131,"{PERSON, LOCATION}","{PERSON, LOCATION}"
10,call_20250109_008.wav,8,15,{PERSON},{PERSON}
11,call_20250328_003.wav,72,161,{PERSON},{PERSON}
12,call_20250305_001.wav,2,6,{PERSON},{PERSON}
13,call_20250115_008.wav,12,9,"{PERSON, LOCATION}",{LOCATION}
14,call_20250415_006.wav,78,35,{LOCATION},{LOCATION}
15,call_20250220_005.wav,6,15,"{PERSON, LOCATION}","{PERSON, LOCATION}"
16,call_20250304_003.wav,3,23,{PERSON},{PERSON}
17,call_20250429_006.wav,16,30,{PERSON},{PERSON}
18,call_20250207_001.wav,35,26,{LOCATION},{LOCATION}
19,call_20250312_001.wav,3,6,{PERSON},{PERSON}
20,call_20250127_001.wav,7,10,{USER_ID},{USER_ID}
21,call_20250106_001.wav,30,42,{PERSON},{PERSON}
22,call_20250505_002.wav,9,6,{PERSON},{PERSON}
23,call_20250327_003.wav,34,24,{PERSON},{PERSON}
24,call_20250429_005.wav,6,12,{PERSON},{PERSON}
25,call_20250128_016.wav,10,12,{PERSON},{PERSON}
26,call_20250203_001.wav,20,12,"{PERSON, LOCATION}","{PERSON, LOCATION}"
27,call_20250327_001.wav,26,16,"{PERSON, LOCATION}","{PERSON, LOCATION}"
28,call_20250305_002.wav,22,41,"{PERSON, LOCATION}","{PERSON, LOCATION}"
29,call_20250219_002.wav,16,55,"{PERSON, LOCATION}","{PERSON, LOCATION}"
30,call_20250303_010.wav,10,16,{PERSON},{PERSON}
31,call_20250213_001.wav,6,22,"{PERSON, LOCATION}","{PERSON, LOCATION}"
32,call_20250213_002.wav,15,24,{PERSON},{PERSON}
33,call_20250214_001.wav,6,9,"{PERSON, LOCATION}","{PERSON, LOCATION}"
34,call_20250318_003.wav,54,54,"{USER_ID, PERSON, LOCATION}","{USER_ID, PERSON, LOCATION}"
35,call_20250114_002.wav,54,12,"{PERSON, LOCATION}",{PERSON}
36,call_20250217_003.wav,24,40,{PERSON},{PERSON}
37,call_20250409_002.wav,25,15,"{PERSON, LOCATION}","{PERSON, LOCATION}"
38,call_20250429_007.wav,30,14,{PERSON},{PERSON}
39,call_20250317_005.wav,36,17,{LOCATION},{LOCATION}

In [14]:
match_report = []
for audio in shared_audios:
    simon_df = df[(df['Audio File'] == audio) & (df['Operator'] == 'Simon')]
    chris_df = df[(df['Audio File'] == audio) & (df['Operator'] == 'Chris')]
    all_labels = set(simon_df['Label']).union(set(chris_df['Label']))
    for label in all_labels:
        simon_spans = set(zip(
            simon_df[simon_df['Label'] == label]['Start'],
            simon_df[simon_df['Label'] == label]['Stop']
        ))
        chris_spans = set(zip(
            chris_df[chris_df['Label'] == label]['Start'],
            chris_df[chris_df['Label'] == label]['Stop']
        ))
        matches = simon_spans & chris_spans
        simon_only = simon_spans - chris_spans
        chris_only = chris_spans - simon_spans
        match_report.append({
            "Audio File": audio,
            "Label": label,
            "Exact Matches": len(matches),
            "Simon Only": len(simon_only),
            "Chris Only": len(chris_only),
            "Simon Only Spans": list(simon_only),
            "Chris Only Spans": list(chris_only)
        })
match_df = pd.DataFrame(match_report)
display(match_df)

,Audio File,Label,Exact Matches,Simon Only,Chris Only,Simon Only Spans,Chris Only Spans
0,call_20250116_004.wav,PERSON,0,6,10,"[(91.0, 94.0), (31.0, 32.0), (24.6, 26.0), (24...","[(25.1, 25.7), (31.2, 31.9), (91.7, 94.8), (25..."
1,call_20250123_001.wav,USER_ID,1,1,1,"[(228.7, 244.0)]","[(229.4, 244.0)]"
2,call_20250123_001.wav,PERSON,0,5,17,"[(64.5, 68.0), (58.0, 59.0), (64.0, 68.0), (84...","[(64.5, 65.0), (67.4, 68.0), (64.3, 65.0), (67..."
3,call_20250127_004.wav,PERSON,0,3,4,"[(103.0, 104.0), (109.0, 110.0), (108.6, 110.0)]","[(108.9, 110.0), (103.0, 104.2), (108.6, 109.8..."
4,call_20250207_004.wav,LOCATION,0,4,2,"[(290.0, 295.0), (296.0, 300.0), (225.0, 228.0...","[(225.7, 228.0), (225.1, 227.7)]"
5,call_20250217_001.wav,PERSON,0,4,4,"[(45.3, 47.0), (45.5, 47.0), (45.0, 46.0), (45...","[(44.9, 46.0), (45.2, 46.4), (45.3, 46.4), (45..."
6,call_20250217_001.wav,LOCATION,0,1,2,"[(42.0, 43.0)]","[(42.5, 43.4), (42.0, 43.2)]"
7,call_20250424_003.wav,PERSON,0,7,24,"[(55.0, 56.0), (31.8, 33.0), (32.0, 33.0), (24...","[(32.2, 33.0), (54.5, 55.3), (22.6, 23.3), (55..."
8,call_20250424_003.wav,LOCATION,0,0,5,[],"[(328.8, 329.3), (328.2, 329.0), (329.6, 330.2..."
9,call_20250325_002.wav,LOCATION,0,4,7,"[(114.0, 116.0), (116.0, 123.0), (116.5, 123.0...","[(114.25, 115.7), (114.4, 115.7), (120.0, 122...."
10,call_20250228_003.wav,USER_ID,1,0,2,[],"[(192.0, 202.2), (192.0, 202.8)]"
11,call_20250228_003.wav,PERSON,3,9,13,"[(218.8, 221.0), (204.6, 206.0), (63.0, 63.6),...","[(62.4, 62.8), (64.6, 65.0), (219.0, 220.6), (..."
12,call_20250107_006.wav,PERSON,1,2,27,"[(39.0, 40.0), (47.0, 50.0)]","[(39.1, 39.9), (48.5, 49.0), (47.4, 47.8), (44..."
13,call_20250107_006.wav,LOCATION,0,1,2,"[(117.0, 119.0)]","[(116.5, 117.3), (117.0, 118.0)]"
14,call_20250312_003.wav,PERSON,0,3,6,"[(22.0, 24.0), (23.0, 23.9), (27.0, 28.0)]","[(27.2, 28.0), (23.0, 24.0), (23.15, 24.0), (2..."
15,call_20250312_003.wav,LOCATION,1,14,40,"[(66.0, 68.0), (58.0, 59.0), (64.0, 68.0), (48...","[(75.0, 76.3), (46.2, 47.1), (65.9, 67.2), (21..."
16,call_20250109_008.wav,PERSON,0,5,10,"[(25.5, 28.0), (25.5, 28.2), (30.0, 31.0), (26...","[(27.6, 28.2), (25.7, 26.3), (25.3, 26.3), (30..."
17,call_20250328_003.wav,PERSON,1,17,46,"[(168.9, 171.0), (163.9, 165.0), (169.2, 171.0...","[(168.8, 169.2), (170.6, 171.2), (22.4, 22.9),..."
18,call_20250305_001.wav,PERSON,0,2,5,"[(29.8, 31.0), (30.0, 31.0)]","[(30.5, 32.0), (29.7, 31.3), (29.75, 31.3), (3..."
19,call_20250115_008.wav,PERSON,0,1,0,"[(38.0, 39.0)]",[]
20,call_20250115_008.wav,LOCATION,0,4,7,"[(51.0, 55.8), (51.0, 55.0), (49.8, 55.8), (51...","[(52.4, 54.0), (50.7, 51.1), (51.1, 51.7), (50..."
21,call_20250415_006.wav,LOCATION,0,21,14,"[(122.0, 123.8), (118.0, 119.0), (123.0, 124.0...","[(138.1, 138.7), (126.9, 128.7), (138.2, 138.7..."
22,call_20250220_005.wav,PERSON,0,3,7,"[(136.0, 138.0), (133.0, 134.0), (132.8, 134.0)]","[(135.8, 137.8), (133.3, 134.3), (135.8, 136.5..."
23,call_20250220_005.wav,LOCATION,0,2,3,"[(298.0, 299.0), (298.0, 300.0)]","[(298.1, 300.2), (298.1, 299.0), (299.1, 300.0)]"
24,call_20250304_003.wav,PERSON,0,3,12,"[(63.0, 64.0), (69.0, 70.0), (73.0, 74.0)]","[(73.0, 73.7), (62.8, 63.6), (73.3, 73.9), (73..."
25,call_20250429_006.wav,PERSON,0,9,12,"[(249.6, 251.0), (31.0, 33.0), (32.0, 33.0), (...","[(253.3, 254.1), (245.5, 246.3), (249.5, 251.0..."
26,call_20250207_001.wav,LOCATION,0,11,18,"[(350.0, 351.0), (346.0, 348.0), (354.6, 357.0...","[(350.0, 350.5), (341.6, 342.5), (354.8, 356.3..."
27,call_20250312_001.wav,PERSON,1,1,4,"[(24.0, 25.0)]","[(24.3, 25.1), (24.0, 24.5), (38.3, 39.3), (23..."
28,call_20250127_001.wav,USER_ID,0,4,4,"[(102.0, 122.0), (125.0, 136.0), (107.0, 136.0...","[(124.8, 137.0), (125.0, 137.0), (103.0, 122.9..."
29,call_20250106_001.wav,PERSON,0,10,20,"[(28.6, 30.0), (118.0, 120.0), (28.1, 30.0), (...","[(119.8, 120.2), (78.5, 79.0), (29.7, 30.4), (..."
30,call_20250505_002.wav,PERSON,0,7,6,"[(29.9, 31.0), (30.6, 31.0), (30.4, 31.0), (30...","[(72.0, 73.0), (30.2, 30.7), (72.5, 73.3), (72..."
31,call_20250327_003.wav,PERSON,0,7,11,"[(65.0, 66.0), (39.0, 40.0), (43.5, 44.0), (40...","[(39.0, 39.7), (43.6, 44.4), (43.3, 43.8), (43..."
32,call_20250429_005.wav,PERSON,1,3,6,"[(66.0, 67.0), (63.0, 63.9), (62.0, 63.0)]","[(62.7, 63.3), (68.1, 69.0), (63.5, 64.3), (62..."
33,call_20250128_016.wav,PERSON,0,8,7,"[(29.5, 30.2), (33.6, 34.5), (34.0, 35.0), (33...","[(37.2, 37.8), (29.4, 30.0), (33.3, 34.6), (29..."
34,call_20250203_001.wav,PERSON,0,4,8,"[(24.0, 25.0), (21.0, 22.0), (27.0, 29.0), (20...","[(24.7, 25.3), (24.3, 24.9), (27.5, 29.0), (21..."
35,call_20250203_001.wav,LOCATION,0,4,3,"[(143.0, 145.2), (143.0, 145.0), (144.0, 146.0...","[(144.8, 145.7), (144.2, 145.2), (144.3, 145.2)]"
36,call_20250327_001.wav,PERSON,1,4,3,"[(94.8, 96.0), (92.0, 93.0), (92.5, 93.0), (92...","[(94.5, 95.3), (92.25, 93.3), (92.5, 93.5)]"
37,call_20250327_001.wav,LOCATION,0,4,6,"[(125.0, 126.0), (122.0, 123.0), (125.1, 126.0...","[(121.9, 122.5), (125.8, 126.8), (125.7, 128.3..."
38,call_20250305_002.wav,PERSON,1,0,12,[],"[(446.75, 447.7), (441.4, 442.0), (441.3, 442...."
39,call_20250305_002.wav,LOCATION,0,8,6,"[(150.0, 152.0), (152.5, 155.0), (152.5, 155.8...","[(150.1, 152.9), (154.75, 155.4), (154.75, 155..."
40,call_20250219_002.wav,PERSON,0,3,9,"[(157.0, 160.0), (156.8, 160.0), (158.0, 159.0)]","[(157.1, 158.0), (158.5, 159.0), (159.0, 160.0..."
41,call_20250219_002.wav,LOCATION,0,5,16,"[(161.0, 161.8), (160.1, 161.0), (161.6, 162.6...","[(158.0, 158.3), (157.75, 158.0), (162.0, 162...."
42,call_20250303_010.wav,PERSON,0,6,9,"[(60.8, 61.0), (58.0, 59.0), (59.9, 61.0), (60...","[(60.5, 61.2), (60.5, 61.7), (58.5, 60.2), (60..."
43,call_20250213_001.wav,PERSON,0,3,13,"[(30.0, 32.0), (34.0, 35.0), (31.0, 32.0)]","[(30.6, 31.5), (30.6, 31.0), (30.6, 31.8), (30..."
44,call_20250213_001.wav,LOCATION,0,2,4,"[(92.5, 96.0), (93.0, 95.0)]","[(31.2, 31.55), (31.5, 31.9), (31.3, 31.9), (3..."
45,call_20250213_002.wav,PERSON,0,11,15,"[(22.0, 27.0), (26.0, 27.0), (22.0, 23.0), (24...","[(27.2, 28.0), (24.8, 25.2), (23.6, 24.0), (26..."
46,call_20250214_001.wav,PERSON,0,3,5,"[(45.0, 46.0), (41.0, 43.0), (44.8, 45.9)]","[(45.4, 45.9), (44.8, 45.25), (44.7, 45.1), (4..."
47,call_20250214_001.wav,LOCATION,0,1,3,"[(54.0, 55.0)]","[(54.0, 54.5), (53.9, 54.3), (54.5, 55.0)]"
48,call_20250318_003.wav,LOCATION,0,2,6,"[(300.0, 303.0), (204.0, 206.0)]","[(300.0, 302.7), (204.15, 206.3), (204.25, 206..."
49,call_20250318_003.wav,USER_ID,0,1,3,"[(420.0, 435.0)]","[(420.5, 435.5), (420.4, 435.5), (420.7, 435.5)]"
50,call_20250318_003.wav,PERSON,1,14,16,"[(382.0, 384.0), (201.0, 202.0), (436.0, 438.0...","[(382.7, 384.1), (200.0, 201.5), (436.45, 438...."
51,call_20250114_002.wav,PERSON,0,20,12,"[(22.001, 24.22), (21.0, 22.0), (22.15, 24.22)...","[(21.5, 22.0), (23.8, 24.1), (22.5, 23.0), (21..."
52,call_20250114_002.wav,LOCATION,0,11,0,"[(31.994, 33.0), (31.0, 33.0), (32.0, 33.0), (...",[]
53,call_20250217_003.wav,PERSON,1,8,12,"[(68.8, 70.0), (65.0, 66.0), (68.7, 70.0), (68...","[(77.6, 78.0), (71.1, 71.4), (71.6, 72.2), (68..."
54,call_20250409_002.wav,PERSON,0,8,5,"[(200.0, 201.0), (199.8, 201.0), (199.6, 201.0...","[(200.0, 200.8), (192.8, 193.6), (199.5, 200.2..."
55,call_20250409_002.wav,LOCATION,0,3,6,"[(271.0, 273.0), (270.8, 273.0), (269.0, 270.0)]","[(269.5, 270.2), (271.1, 272.7), (269.6, 270.4..."
56,call_20250429_007.wav,PERSON,0,17,11,"[(31.0, 31.9), (25.79, 27.0), (26.0, 27.0), (2...","[(97.8, 98.3), (97.5, 98.3), (25.8, 28.5), (30..."
57,call_20250317_005.wav,LOCATION,0,12,9,"[(132.0, 133.5), (82.0, 84.0), (568.0, 569.0),...","[(46.5, 47.2), (413.8, 415.2), (567.7, 568.4),..."

In [17]:
# Define a threshold for "near" (e.g., 1 second)
threshold = 0.06

near_match_report = []
for audio in shared_audios:
    simon_df = df[(df['Audio File'] == audio) & (df['Operator'] == 'Simon')]
    chris_df = df[(df['Audio File'] == audio) & (df['Operator'] == 'Chris')]
    for label in set(simon_df['Label']).intersection(set(chris_df['Label'])):
        simon_spans = simon_df[simon_df['Label'] == label][['Start', 'Stop']].values
        chris_spans = chris_df[chris_df['Label'] == label][['Start', 'Stop']].values
        for s_start, s_stop in simon_spans:
            for c_start, c_stop in chris_spans:
                if abs(s_start - c_start) <= threshold and abs(s_stop - c_stop) <= threshold:
                    near_match_report.append({
                        "Audio File": audio,
                        "Label": label,
                        "Simon Start": s_start,
                        "Simon Stop": s_stop,
                        "Chris Start": c_start,
                        "Chris Stop": c_stop,
                        "Start Diff": abs(s_start - c_start),
                        "Stop Diff": abs(s_stop - c_stop)
                    })
near_match_df = pd.DataFrame(near_match_report)
display(near_match_df)

,Audio File,Label,Simon Start,Simon Stop,Chris Start,Chris Stop,Start Diff,Stop Diff
0,call_20250123_001.wav,USER_ID,229.00,244.00,229.0,244.0,0.00,0.00
1,call_20250123_001.wav,USER_ID,229.00,244.00,229.0,244.0,0.00,0.00
2,call_20250123_001.wav,USER_ID,229.00,244.00,229.0,244.0,0.00,0.00
3,call_20250123_001.wav,USER_ID,229.00,244.00,229.0,244.0,0.00,0.00
4,call_20250123_001.wav,USER_ID,229.00,244.00,229.0,244.0,0.00,0.00
5,call_20250123_001.wav,USER_ID,229.00,244.00,229.0,244.0,0.00,0.00
6,call_20250123_001.wav,USER_ID,229.00,244.00,229.0,244.0,0.00,0.00
7,call_20250123_001.wav,USER_ID,229.00,244.00,229.0,244.0,0.00,0.00
8,call_20250123_001.wav,USER_ID,229.00,244.00,229.0,244.0,0.00,0.00
9,call_20250123_001.wav,USER_ID,229.00,244.00,229.0,244.0,0.00,0.00
10,call_20250123_001.wav,USER_ID,229.00,244.00,229.0,244.0,0.00,0.00
11,call_20250228_003.wav,USER_ID,192.00,204.00,192.0,204.0,0.00,0.00
12,call_20250228_003.wav,USER_ID,192.00,204.00,192.0,204.0,0.00,0.00
13,call_20250228_003.wav,USER_ID,192.00,204.00,192.0,204.0,0.00,0.00
14,call_20250228_003.wav,USER_ID,192.00,204.00,192.0,204.0,0.00,0.00
15,call_20250228_003.wav,USER_ID,192.00,204.00,192.0,204.0,0.00,0.00
16,call_20250228_003.wav,USER_ID,192.00,204.00,192.0,204.0,0.00,0.00
17,call_20250228_003.wav,USER_ID,192.00,204.00,192.0,204.0,0.00,0.00
18,call_20250228_003.wav,USER_ID,192.00,204.00,192.0,204.0,0.00,0.00
19,call_20250228_003.wav,USER_ID,192.00,204.00,192.0,204.0,0.00,0.00
20,call_20250228_003.wav,USER_ID,192.00,204.00,192.0,204.0,0.00,0.00
21,call_20250228_003.wav,USER_ID,192.00,204.00,192.0,204.0,0.00,0.00
22,call_20250228_003.wav,USER_ID,192.00,204.00,192.0,204.0,0.00,0.00
23,call_20250228_003.wav,USER_ID,192.00,204.00,192.0,204.0,0.00,0.00
24,call_20250228_003.wav,USER_ID,192.00,204.00,192.0,204.0,0.00,0.00
25,call_20250228_003.wav,USER_ID,192.00,204.00,192.0,204.0,0.00,0.00
26,call_20250228_003.wav,USER_ID,192.00,204.00,192.0,204.0,0.00,0.00
27,call_20250228_003.wav,USER_ID,192.00,204.00,192.0,204.0,0.00,0.00
28,call_20250228_003.wav,USER_ID,192.00,204.00,192.0,204.0,0.00,0.00
29,call_20250228_003.wav,PERSON,219.60,221.00,219.6,221.0,0.00,0.00
30,call_20250228_003.wav,PERSON,205.00,206.00,205.0,206.0,0.00,0.00
31,call_20250228_003.wav,PERSON,205.00,206.00,205.0,206.0,0.00,0.00
32,call_20250228_003.wav,PERSON,205.00,206.00,205.0,206.0,0.00,0.00
33,call_20250228_003.wav,PERSON,65.00,65.50,65.0,65.5,0.00,0.00
34,call_20250228_003.wav,PERSON,65.00,65.50,65.0,65.5,0.00,0.00
35,call_20250107_006.wav,PERSON,44.00,45.00,44.0,45.0,0.00,0.00
36,call_20250312_003.wav,LOCATION,81.00,82.00,81.0,82.0,0.00,0.00
37,call_20250312_003.wav,LOCATION,81.00,82.00,81.0,82.0,0.00,0.00
38,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
39,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
40,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
41,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
42,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
43,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
44,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
45,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
46,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
47,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
48,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
49,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
50,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
51,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
52,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
53,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
54,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
55,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
56,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
57,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
58,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
59,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
60,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
61,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
62,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
63,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
64,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
65,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
66,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
67,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
68,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
69,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
70,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
71,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
72,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
73,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
74,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
75,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
76,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
77,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
78,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
79,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
80,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
81,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
82,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
83,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
84,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
85,call_20250328_003.wav,PERSON,36.00,37.00,36.0,37.0,0.00,0.00
86,call_20250312_001.wav,PERSON,38.00,39.00,38.0,39.0,0.00,0.00
87,call_20250312_001.wav,PERSON,38.00,39.00,38.0,39.0,0.00,0.00
88,call_20250429_005.wav,PERSON,68.00,69.00,68.0,69.0,0.00,0.00
89,call_20250429_005.wav,PERSON,68.00,69.00,68.0,69.0,0.00,0.00
90,call_20250429_005.wav,PERSON,68.00,69.00,68.0,69.0,0.00,0.00
91,call_20250429_005.wav,PERSON,68.00,69.00,68.0,69.0,0.00,0.00
92,call_20250429_005.wav,PERSON,68.00,69.00,68.0,69.0,0.00,0.00
93,call_20250429_005.wav,PERSON,68.00,69.00,68.0,69.0,0.00,0.00
94,call_20250327_001.wav,PERSON,95.00,96.00,95.0,96.0,0.00,0.00
95,call_20250327_001.wav,PERSON,95.00,96.00,95.0,96.0,0.00,0.00
96,call_20250305_002.wav,PERSON,37.00,40.00,37.0,40.0,0.00,0.00
97,call_20250305_002.wav,PERSON,37.00,40.00,37.0,40.0,0.00,0.00
98,call_20250305_002.wav,PERSON,37.00,40.00,37.0,40.0,0.00,0.00
99,call_20250305_002.wav,PERSON,37.00,40.00,37.0,40.0,0.00,0.00
100,call_20250305_002.wav,PERSON,37.00,40.00,37.0,40.0,0.00,0.00
101,call_20250305_002.wav,PERSON,37.00,40.00,37.0,40.0,0.00,0.00
102,call_20250305_002.wav,PERSON,37.00,40.00,37.0,40.0,0.00,0.00
103,call_20250305_002.wav,PERSON,37.00,40.00,37.0,40.0,0.00,0.00
104,call_20250305_002.wav,PERSON,37.00,40.00,37.0,40.0,0.00,0.00
105,call_20250305_002.wav,PERSON,37.00,40.00,37.0,40.0,0.00,0.00
106,call_20250305_002.wav,PERSON,37.00,40.00,37.0,40.0,0.00,0.00
107,call_20250305_002.wav,PERSON,37.00,40.00,37.0,40.0,0.00,0.00
108,call_20250305_002.wav,PERSON,37.00,40.00,37.0,40.0,0.00,0.00
109,call_20250305_002.wav,PERSON,37.00,40.00,37.0,40.0,0.00,0.00
110,call_20250305_002.wav,PERSON,37.00,40.00,37.0,40.0,0.00,0.00
111,call_20250305_002.wav,PERSON,37.00,40.00,37.0,40.0,0.00,0.00
112,call_20250305_002.wav,PERSON,37.00,40.00,37.0,40.0,0.00,0.00
113,call_20250305_002.wav,PERSON,37.00,40.00,37.0,40.0,0.00,0.00
114,call_20250305_002.wav,PERSON,37.00,40.00,37.0,40.0,0.00,0.00
115,call_20250305_002.wav,PERSON,37.00,40.00,37.0,40.0,0.00,0.00
116,call_20250305_002.wav,PERSON,37.00,40.00,37.0,40.0,0.00,0.00
117,call_20250305_002.wav,PERSON,37.00,40.00,37.0,40.0,0.00,0.00
118,call_20250305_002.wav,PERSON,37.00,40.00,37.0,40.0,0.00,0.00
119,call_20250305_002.wav,PERSON,37.00,40.00,37.0,40.0,0.00,0.00
120,call_20250305_002.wav,PERSON,37.00,40.00,37.0,40.0,0.00,0.00
121,call_20250305_002.wav,PERSON,37.00,40.00,37.0,40.0,0.00,0.00
122,call_20250305_002.wav,PERSON,37.00,40.00,37.0,40.0,0.00,0.00
123,call_20250305_002.wav,PERSON,37.00,40.00,37.0,40.0,0.00,0.00
124,call_20250305_002.wav,PERSON,37.00,40.00,37.0,40.0,0.00,0.00
125,call_20250305_002.wav,PERSON,37.00,40.00,37.0,40.0,0.00,0.00
126,call_20250318_003.wav,PERSON,200.50,202.00,200.5,202.0,0.00,0.00
127,call_20250114_002.wav,PERSON,21.80,22.42,21.8,22.4,0.00,0.02
128,call_20250217_003.wav,PERSON,68.96,70.00,69.0,70.0,0.04,0.00
129,call_20250217_003.wav,PERSON,69.00,70.00,69.0,70.0,0.00,0.00